config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'pomodoros/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :tasks do
    patch :toggle_status
  end
  resources :tasks do
    resources :comments
  end

end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { in: 1..50 }
  validates :content, presence: true
  validates :time_limit, presence: true
  validate :date_check, on: :create
  def date_check
    errors.add(:time_limit, '過去の日付は入力できません') if time_limit.nil? || time_limit < Date.today
  end
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :status, presence: true
  validates :status, inclusion: { in: %w(やってないよ やったよ) }
  enum status: { やってないよ: 0, やったよ: 1 }
  def toggle_status!
    if やってないよ?
      やったよ!
    else
      やってないよ!
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :authenticate_user!, only: [:show, :new, :edit, :update, :destroy, :index]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result.order(created_at: :desc).page(params[:page]).per(5)
    @task_list = Task.where("task.time_limit > ?", DateTime.now).reorder(:time_limit)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "新規タスクを作成しました。"
      else
      render :new
      end
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクの編集を行いました。"
    else
      render :edit
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
    @user = User.find_by(id: @task.user_id)
    @comments = @task.comments
    @comment = @task.comments.build
    unless @task.user_id == current_user.id
      redirect_to tasks_path, notice: '無効な操作が行われました'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました。"
  end

  def toggle_status
    @task.toggle_status!
    @task.save
    redirect_to tasks_path, notice: 'ステータスを更新しました。'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :time_limit, :user_id, { label_ids: [] }, :status )
  end

  def set_task
    #@task = Task.find(params[:id])
    @task = Task.find(params[:id] || params[:task_id])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ) do |form| %>
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= @task.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="task_title">
  <%= form.label :title,"タスク名" %>
  <%= form.text_field :title, class:"form-control"%>
</div>
<div class="task_title">
  <%= form.label :content,"内容" %>
  <%= form.text_area :content, class:"form-control" %>
</div>
<div class="form-group">
  <%= form.label :time_limit, "期限" %>
  <p><%= form.date_field :time_limit, value: Time.now.strftime("%Y-%m-%d"), class:'form-control' %></p>
</div>
<div class="task_title">
  <%= form.label :label, "ラベル" %><br>
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
</div>
<div class="task_title">
  <%= form.label :status, "ステータス" %><br>
  <%= form.label :status, 'やってないよ' %>
</div>
<div class="task_action">
  <th><%= form.submit %></th>
  <th><%= link_to "タスク一覧にもどる", tasks_path, class:"btn btn-warning"  %></th>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="main_h1">タスク編集をする</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="main_h1">タスク一覧</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :time_limit %>
  <%= f.date_field :time_limit_gteq, include_blank: true %>〜<%= f.date_field :time_limit_lteq, include_blank: true %>
  <%= f.label :status %>
  <%= f.select :status_eq, Task.statuses.map{|s|[t("activerecord.enum.status.#{s[0]}"), "#{s[1]}"]} %><br>
  <% Label.all.each_with_index do |label, i| %>
    <%= f.check_box :labels_id_eq_any, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <label for=<%="q_labels_id_eq_any_#{i + 1}" %>><%= label.name %></label>
  <% end %><br>
  <div class="search_action">
    <th><%= f.submit %></th>
    <th><%= link_to '検索条件のクリア', request.path, class:"btn btn-warning" %></th>
  </div>
<% end%>

<br><%= paginate @tasks %>

<table>
  <% @tasks.each do |task| %>
    <div class="task_list">
      <div class="task_row">
        <span><strong>タスク名</strong><%= task.title %></span>
        <span><strong>終了期限: </strong><%= l task.time_limit, format: :long %></span>
        <span><strong>ステータス:</strong><%=link_to task.status, task_toggle_status_path(task), method: :patch %></span>
        <span class="labels">
          <% task.labels.each do |label| %>
            <span>#<%= label.name %></span>
          <% end %>
        </span>
        <span class="index_pomodoros_show"><%= link_to 'ポモドーロ？', pomodoros_show_path %></span>
        <span class="index_tasks_show"><%= link_to '詳細', task_path(task.id) %></span>
        <span class="index_tasks_edit"><%= link_to '編集', edit_task_path(task.id) %></span>
        <span class="index_tasks_delete"><%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></span>
      </div>
    </div>
  <% end %>
</table>
<%= paginate @tasks %>
<br>
<%= link_to '新規作成', new_task_path, class: "link_color", class:"btn btn-warning" %></a>

app/views/tasks/new.html.erb
<h1 class="main_h1">タスクを作成する</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1 class="main_h1">タスク詳細画面</h1>

<div class="task_details">
  <strong>タスク名</strong>
  <p><%= @task.title %></p>
  <strong>内容</strong>
  <p><%= safe_join(@task.content.split("\n"),tag(:br)) %></p>
  <strong>終了期限</strong>
  <p><%= @task.time_limit %></p>
  <strong>
    <strong>Status:</strong>
    <%= link_to @task.status, task_toggle_status_path(@task), method: :patch %>
  </p>
  <strong><% @task.labels.each do |label| %>
    #
    <%= label.name %>
    <% end %></strong>
</div>


<p><%= link_to 'ポモドーロ', pomodoros_show_path, class:"btn btn-warning" %></p>

<div class="container">
  <p id="notice"><%= notice %></p>
  <p>コメント一覧</p>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, task: @task } %>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, task: @task } %>
</div>
<br>
  <p><%= link_to '編集', edit_task_path(@task), class:"btn btn-warning" %>
  <%= link_to '戻る', tasks_path, class:"btn btn-warning" %></p>