config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'pomodoros/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :tasks do
    patch :toggle_status
  end
  resources :tasks do
    resources :comments
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  validates :content, presence: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { in: 1..50 }
  validates :content, presence: true
  validates :time_limit, presence: true
  validate :date_check, on: :create
  def date_check
    errors.add(:time_limit, '過去の日付は入力できません') if time_limit.nil? || time_limit < Date.today
  end
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :status, presence: true
  validates :status, inclusion: { in: %w(やってないよ やったよ) }
  enum status: { やってないよ: 0, やったよ: 1 }
  def toggle_status!
    if やってないよ?
      やったよ!
    else
      やってないよ!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :trackable

  validates :name, presence: true
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'guest'
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'admin_guest'
      user.admin = true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!  # ログイン済ユーザーのみにアクセスを許可する
  before_action :configure_permitted_parameters, if: :devise_controller?# deviseコントローラーにストロングパラメータを追加する

  def after_sign_in_path_for(resource)
    tasks_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])# サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])# アカウント編集の時にnameのストロングパラメータを追加
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task, only: [:create, :edit, :update]

  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to task_path(@task), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = @task.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @task.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:task_id, :content, :user_id)
  end
  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :authenticate_user!, only: [:show, :new, :edit, :update, :destroy, :index]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result.order(created_at: :desc).page(params[:page]).per(5)
    @task_list = Task.where("task.time_limit > ?", DateTime.now).reorder(:time_limit)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "新規タスクを作成しました。"
      else
      render :new
      end
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクの編集を行いました。"
    else
      render :edit
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
    @user = User.find_by(id: @task.user_id)
    @comments = @task.comments
    @comment = @task.comments.build
    unless @task.user_id == current_user.id
      redirect_to tasks_path, notice: '無効な操作が行われました'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました。"
  end

  def toggle_status
    @task.toggle_status!
    @task.save
    redirect_to tasks_path, notice: 'ステータスを更新しました。'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :time_limit, :user_id, { label_ids: [] }, :status )
  end

  def set_task
    #@task = Task.find(params[:id])
    @task = Task.find(params[:id] || params[:task_id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to tasks_path, notice: '無効な操作が行われました'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pomodoros_helper.rb
module PomodorosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<html>
  <head>
    <title>Pomotas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= controller.controller_name %>_<%= controller.action_name %>">
    <header>
      <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <h1><%= link_to "Pomotas", root_path %></h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <% if user_signed_in? %>
                  <% if current_user.admin? %>
                    <li class="nav-item active"><%= link_to "管理画面", rails_admin_path %></li>
                  <% end %>
                  <li class="nav-item"><%= link_to "Task List", tasks_path %></li>
                  <li class="nav-item"><%= link_to "My Page", user_path(current_user.id) %></li>
                  <li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                  <li class="nav-item"><%= link_to "Back to Top", root_path %></li>
                <% else %>
                  <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path %></li>
                  <li class="nav-item"><%= link_to "Log In", new_user_session_path %></li>
                  <li class="nav-item"><%= link_to "Back to Top", root_path %></li>
                <% end %>
              </ul>
            </div>
          </nav>
      </div>
    </header>
    <article class="main_content">
    <div class="container">
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    </article>
    <footer>
      <div class="container">
        <% date = Time.new %>
          <p class="copyright"><small>&#169; <%= date.year.to_s %> Pomotas All Rights Reserved.</small></p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>